/*
1. some pattern? hard to realise yet useful
2. same repo for all labs(5-8)
3. lab with multithreading will be changed to be made harder
4. helios must be used
5. compile and run lab everywhere(probably jar)
6. classes generated by se.ifmo will be conflicting, DONT ask, just decide and reason
7. user is dumb, for instance flags of 1 command for another
8. add {element} - does not MEAN that element is to be specified immediately
Must enter interactive form(and users are dumb)
Should be user-friendly
9. careful with copying, helios?
10. error messages
11. Validation! everything that can be written in terminal must work
12. should check
13. if not validated - better to exit to main menu/go through and then check and reask
14. MUST never exit program, unless user specifically asks to exit
15. command entity?
16. Separate entity for working with input
17. Command history
18 Check for overflow, work with large numbers?
19. Save exceptions?
20. Logging? (my idea)
21. External libraries can be used to READ DATA, not validate!
*/

import java.io.File;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        /*
        1. How to read from console? By line, by symbol?
        Need to work with string, its validation
        */
        System.out.println(System.getProperty("user.dir"));
        Scanner sc =  new Scanner(System.in);

        try {
            sc = new Scanner(new File("input.txt"));
        }
        catch (Exception e) {
            System.err.println("File not found!");
        }

        while (sc.hasNextLine()) {
            String input = sc.nextLine();

            System.out.println(input);
            if (input.equals("exit")) {
                System.exit(0);
            }

            if  (input.equals("help")) {
                System.out.println("List of commands");
            }
        }
    }
}


/* help
1. Menu
2. Input
3. Validation
4. Create command object, add to history
5. Action if command is correct
    Maybe ask for additional input
    Print error, maybe save?
*/

/*
Project structure(entities):
Main
Invoker - whatever it is
Command
Validation
Models
Container(my idea)
Smth from se.ifmo(perhaps container entity)
Logger
File module: producer, validator, loader. External libraries can be used to READ DATA, not validate!
 */